app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['prefix'=>'admin', 'middleware'=>'auth.checkrole:deliveryman', 'as'=>'admin.'],function(){

	Route::get('categories',['as' => 'categories.index', 'uses' => 'CategoriesController@index']);
	Route::get('categories/create',['as' => 'categories.create', 'uses' => 'CategoriesController@create']);
	Route::get('categories/edit/{id}',['as' => 'categories.edit', 'uses' => 'CategoriesController@edit']);
	Route::post('categories/update/{id}',['as' => 'categories.update', 'uses' => 'CategoriesController@update']);
	Route::post('categories/store',['as' => 'categories.store', 'uses' => 'CategoriesController@store']);

	Route::get('clients',['as' => 'clients.index', 'uses' => 'ClientsController@index']);
	Route::get('clients/create',['as' => 'clients.create', 'uses' => 'ClientsController@create']);
	Route::get('clients/edit/{id}',['as' => 'clients.edit', 'uses' => 'ClientsController@edit']);
	Route::post('clients/update/{id}',['as' => 'clients.update', 'uses' => 'ClientsController@update']);
	Route::post('clients/store',['as' => 'clients.store', 'uses' => 'ClientsController@store']);

	Route::get('products',['as' => 'products.index', 'uses' => 'ProductsController@index']);
	Route::get('products/create',['as' => 'products.create', 'uses' => 'ProductsController@create']);
	Route::get('products/edit/{id}',['as' => 'products.edit', 'uses' => 'ProductsController@edit']);
	Route::get('products/destroy/{id}',['as' => 'products.delete', 'uses' => 'ProductsController@destroy']);
	Route::post('products/update/{id}',['as' => 'products.update', 'uses' => 'ProductsController@update']);
	Route::post('products/store',['as' => 'products.store', 'uses' => 'ProductsController@store']);

	Route::get('orders',['as' => 'orders.index', 'uses' => 'OrdersController@index']);
	Route::get('orders/{id}',['as' => 'orders.edit', 'uses' => 'OrdersController@edit']);
	Route::post('orders/update/{id}',['as' => 'orders.update', 'uses' => 'OrdersController@update']);

	Route::get('cupoms',['as' => 'cupoms.index', 'uses' => 'CupomsController@index']);
	Route::get('cupoms/create',['as' => 'cupoms.create', 'uses' => 'CupomsController@create']);
	Route::get('cupoms/{id}',['as' => 'cupoms.edit', 'uses' => 'CupomsController@edit']);
	Route::post('cupoms/update/{id}',['as' => 'cupoms.update', 'uses' => 'CupomsController@update']);
	Route::post('cupoms/store',['as' => 'cupoms.store', 'uses' => 'CupomsController@store']);
});

Route::group(['prefix'=>'customer', 'middleware'=>'auth.checkrole:client', 'as'=>'customer.'], function(){
	Route::get('order', ['as'=>'order.index', 'uses'=>'CheckoutController@index']);
	Route::get('order/create', ['as'=>'order.create', 'uses'=>'CheckoutController@create']);
	Route::post('order/store', ['as'=>'order.store', 'uses'=>'CheckoutController@store']);
});

//qnd for configurar o cors usar composer require barryvdh/laravel-cors 0.7.x
Route::group(['middleware'=>'cors'],function(){

	Route::post('oauth/access_token', function() {
	    return Response::json(Authorizer::issueAccessToken());
	});

	Route::group(['prefix'=>'api', 'middleware'=>'oauth', 'as'=>'api.'],function(){
		
		Route::group(['prefix'=>'client', 'middleware'=>'oauth.checkrole:client', 'as'=>'client.'],function(){
			
			Route::resource('order','Api\Client\ClientCheckoutController',['except' => ['create','edit','destroy']]);
			Route::get('products','Api\Client\ClientProductController@index');
			
		});
		
		Route::group(['prefix'=>'deliveryman', 'middleware'=>'oauth.checkrole:deliveryman', 'as'=>'deliveryman.'],function(){
			
			Route::resource('order','Api\Deliveryman\DeliverymanCheckoutController',['except' => ['create','edit','destroy','store']]);
			Route::patch('order/{id}/update-status',[
				'uses'=>'Api\Deliveryman\DeliverymanCheckoutController@updateStatus',
				'as'=>'orders.update_status']);
			Route::post('order/{id}/geo',['as' => 'orders.geo', 'uses' => 'Api\Deliveryman\DeliverymanCheckoutController@geo']);

		});
		Route::get('authenticated','Api\UserController@authenticated');	
		Route::get('cupom/{code}','Api\CupomController@show');	
	});
});

app/Models/Product.php
<?php

namespace Delivery\Models;

use Illuminate\Database\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

class Product extends Model implements Transformable
{
    use TransformableTrait;

    protected $fillable = [
        'category_id',
        'name',
        'description',
        'price'
    ];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

}

app/Http/Controllers/ProductsController.php
<?php

namespace Delivery\Http\Controllers;

use Illuminate\Http\Request;

use Delivery\Http\Requests;
use Delivery\Http\Controllers\Controller;
use Delivery\Repositories\ProductRepository;
use Delivery\Repositories\CategoryRepository;
use Delivery\Http\Requests\AdminCategoryRequest;
use Delivery\Http\Requests\AdminProductRequest;

class ProductsController extends Controller
{
	private $repository;

	public function __construct(ProductRepository $repository, CategoryRepository $categoryRepository)
	{
        $this->repository = $repository;

		$this->categoryRepository = $categoryRepository;
	}

    public function index()
    {
    	$products = $this->repository->paginate(5);

    	return view('admin.products.index',compact('products'));
    }

    public function create()
    {
        $categories = $this->categoryRepository->lists('name', 'id');

    	return view('admin.products.create', compact('categories'));
    }

    public function store(AdminProductRequest $request)
    {
    	$this->repository->create($request->all());

        return redirect()->route('admin.products.index');
    }

    public function edit($id)
    {
        $product = $this->repository->find($id);
        $categories = $this->categoryRepository->lists('name', 'id');

    	return view('admin.products.edit', compact('product','categories'));
    }

    public function update(AdminProductRequest $request, $id)
    {
    	$this->repository->update($request->all(), $id);
    	return redirect()->route('admin.products.index');
    }
    public function destroy($id)
    {
        $this->repository->delete($id);
        return redirect()->route('admin.products.index');
    }
}

resources/views/admin/products/_form.blade.php
  <div class="form-group">
 	{!! Form::label('Category','Categoria:')!!}
 	{!! Form::select('category_id', $categories, null,['class'=>'form-control'])!!}
 </div>

 <div class="form-group">
 	{!! Form::label('Name','Nome:')!!}
 	{!! Form::text('name', null,['class'=>'form-control'])!!}
 </div>

 <div class="form-group">
 	{!! Form::label('Description','Descrição:')!!}
 	{!! Form::textarea('description', null,['class'=>'form-control'])!!}
 </div>

 <div class="form-group">
 	{!! Form::label('Price','Preço:')!!}
 	{!! Form::text('price', null,['class'=>'form-control'])!!}
 </div>

resources/views/admin/products/create.blade.php
@extends('app')

@section('content')

<div class="container">
	<h3>Novo Produto</h3>
	<br>
	<br>
	@include('errors._check')

	{!! Form::open(['route'=>'admin.products.store', 'class'=>'form'])!!}

	@include('admin.products._form')

	 <div class="form-group">
	 	{!! Form::submit('Criar Produto', ['class'=>'btn btn-primary'])!!}
	 </div>

	{!! Form::close()!!}

</div>

@endsection

resources/views/admin/products/edit.blade.php
@extends('app')

@section('content')

<div class="container">
	<h3>Editar Produtos: {{$product->name}}</h3>
	<br><br>
	
	@include('errors._check')
	
	{!! Form::model($product, ['route'=>['admin.products.update', $product->id]])!!}

	 @include('admin.products._form')

	 <div class="form-group">
	 	{!! Form::submit('Salvar Produto', ['class'=>'btn btn-primary'])!!}
	 </div>

	{!! Form::close()!!}

</div>

@endsection

resources/views/admin/products/index.blade.php
@extends('app')

@section('content')

<div class="container">
	<h3>Produtos</h3>
	<br>
	<a href="{{ route('admin.products.create')}}" class="btn btn-default">Novo Produto</a>
	<br>
	<table class="table">
		<thead>
			<tr>
				<th>ID</th>
				<th>Produto</th>
				<th>Categoria</th>
				<th>Preço</th>
				<th>Ação</th>
			</tr>
		<tbody>
			@foreach($products as $product)
			<tr>
				<td>{{$product->id}}</td>
				<td>{{$product->name}}</td>
				<td>{{$product->price}}</td>
				<td>{{$product->category->name}}</td>
				<td>
					<a href="{{route('admin.products.edit',['id'=>$product->id])}}" class="btn btn-default btn-sm">Editar</a>
					<a href="{{route('admin.products.delete',['id'=>$product->id])}}" class="btn btn-danger btn-sm">Excluir</a>
				</td>
			</tr>
			@endforeach
		</tbody>
		</thead>
	</table>
	{!! $products->render() !!}

</div>

@endsection