app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['prefix'=>'admin', 'middleware'=>'auth.checkrole:deliveryman', 'as'=>'admin.'],function(){

	Route::get('categories',['as' => 'categories.index', 'uses' => 'CategoriesController@index']);
	Route::get('categories/create',['as' => 'categories.create', 'uses' => 'CategoriesController@create']);
	Route::get('categories/edit/{id}',['as' => 'categories.edit', 'uses' => 'CategoriesController@edit']);
	Route::post('categories/update/{id}',['as' => 'categories.update', 'uses' => 'CategoriesController@update']);
	Route::post('categories/store',['as' => 'categories.store', 'uses' => 'CategoriesController@store']);

	Route::get('clients',['as' => 'clients.index', 'uses' => 'ClientsController@index']);
	Route::get('clients/create',['as' => 'clients.create', 'uses' => 'ClientsController@create']);
	Route::get('clients/edit/{id}',['as' => 'clients.edit', 'uses' => 'ClientsController@edit']);
	Route::post('clients/update/{id}',['as' => 'clients.update', 'uses' => 'ClientsController@update']);
	Route::post('clients/store',['as' => 'clients.store', 'uses' => 'ClientsController@store']);

	Route::get('products',['as' => 'products.index', 'uses' => 'ProductsController@index']);
	Route::get('products/create',['as' => 'products.create', 'uses' => 'ProductsController@create']);
	Route::get('products/edit/{id}',['as' => 'products.edit', 'uses' => 'ProductsController@edit']);
	Route::get('products/destroy/{id}',['as' => 'products.delete', 'uses' => 'ProductsController@destroy']);
	Route::post('products/update/{id}',['as' => 'products.update', 'uses' => 'ProductsController@update']);
	Route::post('products/store',['as' => 'products.store', 'uses' => 'ProductsController@store']);

	Route::get('orders',['as' => 'orders.index', 'uses' => 'OrdersController@index']);
	Route::get('orders/{id}',['as' => 'orders.edit', 'uses' => 'OrdersController@edit']);
	Route::post('orders/update/{id}',['as' => 'orders.update', 'uses' => 'OrdersController@update']);

	Route::get('cupoms',['as' => 'cupoms.index', 'uses' => 'CupomsController@index']);
	Route::get('cupoms/create',['as' => 'cupoms.create', 'uses' => 'CupomsController@create']);
	Route::get('cupoms/{id}',['as' => 'cupoms.edit', 'uses' => 'CupomsController@edit']);
	Route::post('cupoms/update/{id}',['as' => 'cupoms.update', 'uses' => 'CupomsController@update']);
	Route::post('cupoms/store',['as' => 'cupoms.store', 'uses' => 'CupomsController@store']);
});

Route::group(['prefix'=>'customer', 'middleware'=>'auth.checkrole:client', 'as'=>'customer.'], function(){
	Route::get('order', ['as'=>'order.index', 'uses'=>'CheckoutController@index']);
	Route::get('order/create', ['as'=>'order.create', 'uses'=>'CheckoutController@create']);
	Route::post('order/store', ['as'=>'order.store', 'uses'=>'CheckoutController@store']);
});

//qnd for configurar o cors usar composer require barryvdh/laravel-cors 0.7.x
Route::group(['middleware'=>'cors'],function(){

	Route::post('oauth/access_token', function() {
	    return Response::json(Authorizer::issueAccessToken());
	});

	Route::group(['prefix'=>'api', 'middleware'=>'oauth', 'as'=>'api.'],function(){
		
		Route::group(['prefix'=>'client', 'middleware'=>'oauth.checkrole:client', 'as'=>'client.'],function(){
			
			Route::resource('order','Api\Client\ClientCheckoutController',['except' => ['create','edit','destroy']]);
			Route::get('products','Api\Client\ClientProductController@index');
			
		});
		
		Route::group(['prefix'=>'deliveryman', 'middleware'=>'oauth.checkrole:deliveryman', 'as'=>'deliveryman.'],function(){
			
			Route::resource('order','Api\Deliveryman\DeliverymanCheckoutController',['except' => ['create','edit','destroy','store']]);
			Route::patch('order/{id}/update-status',[
				'uses'=>'Api\Deliveryman\DeliverymanCheckoutController@updateStatus',
				'as'=>'orders.update_status']);
			Route::post('order/{id}/geo',['as' => 'orders.geo', 'uses' => 'Api\Deliveryman\DeliverymanCheckoutController@geo']);

		});
		Route::get('authenticated','Api\UserController@authenticated');	
		Route::get('cupom/{code}','Api\CupomController@show');	
	});
});

app/Models/Order.php
<?php

namespace Delivery\Models;

use Illuminate\Database\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

class Order extends Model implements Transformable
{
    use TransformableTrait;

     protected $fillable = [
    	'client_id',
    	'user_deliveryman_id',
    	'total',
        'status',
    	'cupom_id',
    ];

    public function transform()
    {
        return [
            'order'=>$this->id,
            'items'=>$this->items
        ];
    }

    public function cupom()
    {
        return $this->belongsTo(Cupom::class);
    }
    
    public function client()
    {
        return $this->belongsTo(Client::class);
    }

    public function items()
    {
    	return $this->hasMany(OrderItem::class);
    } 

    public function deliveryman()
    {
    	return $this->belongsTo(User::class, 'user_deliveryman_id', 'id');
        //informa que o user_deliveryman_id faz referencia ao id da tabela User
    }

    public function products()
    {
    	return $this->hasMany(Product::class);
    }

}

app/Http/Controllers/OrdersController.php
<?php

namespace Delivery\Http\Controllers;

use Delivery\Http\Controllers\Controller;
use Delivery\Http\Requests;
use Delivery\Http\Requests\AdminCategoryRequest;
use Delivery\Repositories\OrderRepository;
use Delivery\Repositories\UserRepository;
use Illuminate\Http\Request;

class OrdersController extends Controller
{
	private $orderRepository;

	public function __construct(OrderRepository $orderRepository)
	{
		$this->orderRepository = $orderRepository;
	}

    public function index()
    {
        $orders = $this->orderRepository->paginate(5);

        return view('admin.orders.index', compact('orders'));
    }

    public function edit($id, UserRepository $userRepository)
    {
    	$list_status = [0 => 'Pendente', 1 => 'A caminho', 2 => 'Entregue'];

    	$order = $this->orderRepository->find($id);

    	// $deliveryman = $userRepository->findWhere(['role'=>'deliveryman']);
    	$deliveryman = $userRepository->getDeliverymen();
    	//O getDeliverymen é criado no userRepositoryEloquent

    	return view('admin.orders.edit', compact('order','list_status', 'deliveryman'));
    }

    public function update(Request $request, $id)
    {
    	$all = $request->all();
    	$this->orderRepository->update($all,$id);

    	return redirect()->route('admin.orders.index');
    }
}

resources/views/customer/order/create.blade.php
@extends('app')

@section('content')

<div class="container">
	<h3>Novo Pedido</h3>
	<br>
	<br>
	@include('errors._check')

	<div class="container">
	{!! Form::open(['route'=>'customer.order.store', 'class'=>'form'])!!}
		<div class="form-group">
			<label for="">Total:</label>
			<p id="total"></p>
			<a href="#" class="btn btn-default" id="btnNewItem">Novo Item</a>

			<table class="table table-border">
				<thead>
					<tr>
						<th>Produto</th>
						<th>Quantidade</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>
							<select class="form-control" name="items[0][product_id]">
								@foreach($products as $p)
									<option value="{{$p->id}}" data-price="{{$p->price}}">{{$p->name}} --- {{$p->price}}</option>
								@endforeach
							</select>
						</td>
						<td>
							{!! Form::text('items[0][qtd]',1,['class'=>'form-control'])!!}
						</td>
					</tr>
				</tbody>
			</table>
		</div>
		<div class="form-group">
			{!! Form::submit('Criar pedido',['class'=>'btn btn-primary'])!!}
		</div>
	{!! Form::close() !!}
	</div>

@endsection

@section('post-script')
	<script>
		
		$('#btnNewItem').click(function(){
			var row = $('table tbody > tr:last'),
				newRow = row.clone(),
				length = $("table tbody tr").length;

			newRow.find('td').each(function(){
				var td = $(this),
					input = td.find('input, select'),
					name = input.attr('name');
				input.attr('name', name.replace((length - 1) + "",length + ""));
			});
			newRow.find('input').val(1);
			newRow.insertAfter(row);
			calculateTotal();
		});

		$(document.body).on('click','select',function() {
			calculateTotal();
		});
		
		$(document.body).on('blur','input', function(){
			calculateTotal();
		});


		function calculateTotal(){

			var total = 0,
				trLen = $('table tbody tr').length,
				tr = null, price, qtd;

			for (var i = 0; i < trLen; i++)
			{
				tr = $('table tbody tr').eq(i);
				//o eq(i) foca na implementação de i
				price = tr.find(':selected').data('price');
				//o data('price') é referente ao data-price do option
				qtd = tr.find('input').val();
				total += price * qtd;
			}

			$('#total').html(total);	
		}
	</script>
@endsection

resources/views/customer/order/index.blade.php
@extends('app')

@section('content')

<div class="container">
	<h3>Novo Pedido</h3>
	<br>
	<br>
	@include('errors._check')
	<a href="{{route('customer.order.create')}}" class="btn btn-default">Novo Pedido</a>
	<br>
	<br>
	<table class="table table-bordered">
		<thead>
			<tr>
				<th>ID</th>
				<th>Total</th>
				<th>Status</th>
			</tr>
		</thead>
		<tbody>
		@foreach($orders as $order)
			<tr>
				<td>{{$order->id}}</td>
				<td>{{$order->total}}</td>
				<td>{{$order->status}}</td>
			</tr>
		@endforeach
		</tbody>
	</table>
	{!! $orders->render() !!}
@endsection